source 'https://rubygems.org'


gem 'rails', '4.2.6'
gem 'rails-api', '0.4.0'
gem 'active_model_serializers', '0.10.0.rc4'
gem 'sqlite3'
gem 'bcrypt', '~> 3.1.7'
gem 'jbuilder', '~> 2.0'
# bundle exec rake doc:rails generates the API under doc/api.
gem 'sdoc', '~> 0.4.0', group: :doc

gem 'sorcery'
gem 'cancancan', '~> 1.10'
gem 'rack-cors', :require => 'rack/cors'

group :development, :test do
  gem 'puma' # lets use puma instead of webrick for development
  gem 'foreman'
  gem 'pry-byebug'
  gem 'better_errors'
  gem 'database_cleaner'
  gem 'rails-erd'
end
